version: '3.7'
services:
  mysql:
    build: ./backend/docker/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      # root password
      MYSQL_ROOT_PASSWORD: password
    container_name: register-users-mysql 
    # fix "Public Key Retrieval is not allowed" when attempting to connect with DBeaver
    command: --default-authentication-plugin=mysql_native_password 
  node:
    build:
      context: ./backend
      dockerfile: ./docker/node/Dockerfile
    environment:
      NODE_ENV: "development-docker"
    container_name: register-users-backend
    volumes:
      # mount project folder
      - ./backend:/app
      # do not mount node_modules folder
      - /app/node_modules
    ports:
      - "5000:5000"
      - "9229:9229"
    depends_on:
      - "mysql"  
    #tty: true  
    command: npm run start:dev
